<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="system_tests.TestSystem-20240229023935" tests="2" file="system_tests.py" time="0.016" timestamp="2024-02-29T02:39:35" failures="0" errors="1" skipped="0">
	<testcase classname="system_tests.TestSystem" name="test_login" time="0.000" timestamp="2024-02-29T02:39:35"/>
	<testcase classname="system_tests.TestSystem" name="test_register_customer" time="0.016" timestamp="2024-02-29T02:39:35">
		<error type="AttributeError" message="'Customer' object has no attribute 'firstname'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Khuu Bach Thy\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "C:\Users\Khuu Bach Thy\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Khuu Bach Thy\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "d:\downloads\software_engineering\src\unittest\python\system_tests.py", line 25, in test_register_customer
    self.assertEqual(new_customer.firstname, "John")
    ^^^^^^^^^^^^^^^^^
AttributeError: 'Customer' object has no attribute 'firstname'
]]></error>
	</testcase>
</testsuite>
